# Generated by Django 5.0.4 on 2024-05-05 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=100)),
                ('cpf_cliente', models.CharField(max_length=18, unique=True)),
                ('tel_cliente', models.CharField(max_length=14)),
                ('end_cliente', models.CharField(max_length=150)),
                ('rg_cliente', models.CharField(blank=True, max_length=20)),
                ('data_nasc_cliente', models.DateField(blank=True, null=True)),
                ('cep_cliente', models.CharField(blank=True, max_length=9)),
                ('observacao_cliente', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fantasia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fantasia', models.CharField(max_length=60)),
                ('estoque_fantasia', models.IntegerField(blank=True, null=True)),
                ('observacao_fantasia', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_usuario', models.CharField(max_length=30)),
                ('email_usuario', models.EmailField(max_length=80, unique=True)),
                ('senha_usuario', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='ClienteFantasia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio_fantasia', models.DateTimeField()),
                ('data_fim_fantasia', models.DateTimeField(blank=True, null=True)),
                ('baixa_fantasia', models.CharField(max_length=1)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle.cliente')),
                ('fantasia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle.fantasia')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle.usuario'),
        ),
        migrations.AddConstraint(
            model_name='clientefantasia',
            constraint=models.UniqueConstraint(fields=('cliente', 'fantasia', 'data_inicio_fantasia'), name='unique_cliente_fantasia_data_inicio'),
        ),
    ]
