# Generated by Django 5.0.4 on 2024-05-05 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fantasia',
            name='imagem_fantasia',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_fantasias/'),
        ),
    ]
