# Generated by Django 5.0.4 on 2024-05-05 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0003_alter_clientefantasia_data_fim_fantasia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='email_usuario',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nome_usuario',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
