# Generated by Django 5.0.4 on 2024-05-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0006_clientefantasia_preco_fantasia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='end_cliente',
            new_name='logradouro_cliente',
        ),
        migrations.AddField(
            model_name='cliente',
            name='bairro_logradouro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='complemento_logradouro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='municipio_logradouro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='num_logradouro',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='uf_logradouro',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
