# Generated by Django 5.0.4 on 2024-06-14 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0007_rename_end_cliente_cliente_logradouro_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientefantasia',
            name='tipo_fantasia',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
