# Generated by Django 5.0.4 on 2024-06-15 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0008_clientefantasia_tipo_fantasia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientefantasia',
            name='fantasia',
            field=models.CharField(max_length=80),
        ),
    ]
