# Generated by Django 5.0.4 on 2024-06-15 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0009_alter_clientefantasia_fantasia'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='clientefantasia',
            name='unique_cliente_fantasia_data_inicio',
        ),
    ]
