# Generated by Django 5.0.4 on 2024-06-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0010_remove_clientefantasia_unique_cliente_fantasia_data_inicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='rg_cliente',
        ),
        migrations.AddField(
            model_name='cliente',
            name='email_cliente',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tel2_cliente',
            field=models.CharField(max_length=14, null=True),
        ),
    ]
