# Generated by Django 5.0.6 on 2024-06-26 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0011_remove_cliente_rg_cliente_cliente_email_cliente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_tipo', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='fantasia',
            name='estoque_fantasia',
        ),
        migrations.RemoveField(
            model_name='fantasia',
            name='imagem_fantasia',
        ),
        migrations.RemoveField(
            model_name='fantasia',
            name='observacao_fantasia',
        ),
        migrations.AddField(
            model_name='fantasia',
            name='preco_aluguel',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='fantasia',
            name='preco_venda',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='fantasia',
            name='tipo_fantasia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='controle.tipo'),
            preserve_default=False,
        ),
    ]
