# Generated by Django 5.0.6 on 2024-07-17 17:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0013_alter_cliente_cpf_cliente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.UniqueConstraint(fields=('cpf_cliente', 'usuario'), name='unique_cliente_cpf_usuario'),
        ),
    ]
