# Generated by Django 5.0.6 on 2024-07-17 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0016_rename_tipo_fantasia_clientefantasia_tipo_transacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientefantasia',
            name='fantasia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle.fantasia'),
        ),
        migrations.AlterField(
            model_name='fantasia',
            name='nome_fantasia',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
