# Generated by Django 5.0.6 on 2024-07-17 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0017_alter_clientefantasia_fantasia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tel2_cliente',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
