# Generated by Django 5.0.4 on 2024-08-04 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0020_formapagamento_clientefantasia_forma_pagamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formapagamento',
            name='usuario',
        ),
    ]
