# Generated by Django 5.0.4 on 2024-08-04 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0021_remove_formapagamento_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fantasia',
            name='nome_fantasia',
            field=models.CharField(max_length=60),
        ),
    ]
